from banco_dados import BancoDeDados

# Inicializa o banco de dados
banco = BancoDeDados()

# Lista de pastas a serem inseridas
pastas = [
    "00046 - PROJECT SERVIÇOS EM INFORMÁTICA LTDA ME",
    "00090 - PEREIRA FILHO PARTICIPAÇÕES SOCIETÁRIAS LTDA",
    "00135 - CEZAR BITENCOURT - DF",
    "00145 - ARKO ADVICE PESQUISAS LTDA",
    "00147 - ADVOCACIA MURILLO DE ARAGÃO",
    "00180 - CEZAR ROBERTO BITENCOURT E CIA LTDA - RS",
    "00202 - TIPE PARTICIPAÇÕES SOCIETÁRIAS LTDA",
    "00227 - SAWASDEE PARTICIPAÇÕES SOCIETÁRIAS LTDA",
    "00275 - TECNICA CONSULTORIA EMPRESARIAL EIRELI",
    "00290 - SOFIA COELHO ARAUJO - SOCIEDADE INDIVIDUAL DE ADVOCACIA",
    "00295 - A J MEDICINA INTEGRATIVA LTDA",
    "00357 - TANZ DANÇA E FORMAÇÃO EIRELI",
    "00358 - DIREITO E JUSTIÇA COMÉRCIO DE LIVROS E EVENTOS JURÍDICOS LTDA",
    "00371 - GLUCK AUF PLATZ IMÓVEIS - EIRELI",
    "00382 - MULTIPLANO SERVIÇOS LTDA",
    "00401 - SOUZA NETO TARTARINI ADVOGADOS",
    "00408 - MIRO TEIXEIRA ADVOGADOS ASSOCIADOS",
    "00416 - SHANABI EMPREENDIMENTOS E PARTICIPAÇÕES LTDA",
    "00430 - CPEA - CENTRO DE PRODUÇÃO DE ENERGIA E ALIMENTOS LTDA",
    "00444 - MORATO CONSULTORIA ECONÔMICA E FINANCEIRA LTDA",
    "00447 - CEZAR BITENCOURT - TO",
    "00487 - GUSTAVO ADOLPHO DANTAS SOUTO - SOCIEDADE INDIVIDUAL DE ADVOCACIA",
    "00493 - GAUDIUM PARTICIPACOES SOCIETARIAS SA",
    "00494 - MORGAN ADMINISTRADORA DE BENS LTDA",
    "00495 - FIX ASSESSORIA EM GOVERNANÇA E GESTÃO SA",
    "00516 - REDE GOVERNANÇA BRASIL",
    "00536 - SYX CONSULTORIA EMPRESARIAL LTDA",
    "00555 - VL COMÉRCIO DE ELETRÔNICOS LTDA",
    "00590 - MASSA E HENRIQUE SOUSA ADVOGADOS ASSOCIADOS",
    "00603 - ZAAD PARTICIPAÇÕES SOCIETÁRIAS LTDA",
    "00611 - ANDREIS & ADVOGADOS ASSOCIADOS",
    "00642 - RODRIGO CARNEIRO DE SOUSA AMENO SOCIEDADE",
    "00644 - ROSSANO REOLON SOCIEDADE INDIVIDUAL E ADVOCACIA",
    "00645 - CONSULTORIA NOTORIAL DO BRASIL LTDA",
    "00646 - RODRIGO ROCHA DE SOUZA SOCIEDADE INDIVIDUAL DE ADVOCACIA",
    "00648 - IN PROPRIO BEAUTY COSMETICOS LTDA",
    "00652 - REMOVE LASER LTDA",
    "00654 - MRR PARTICIPAÇÕES SOCIETÁRIAS LTDA",
    "00667 - BUCCHIANERI ADVOCACIA",
    "00700 - ALPINA PARTICIPAÇÕES LTDA"
]

# Insere as pastas no banco de dados
banco.inserir_pastas(pastas)

# Lista todas as pastas para confirmar a inserção
todas_pastas = banco.listar_todas_pastas()
print("Pastas no banco de dados:")
for pasta in todas_pastas:
    print(pasta)

# Fecha a conexão com o banco
banco.fechar_conexao()
